# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Hugo Charles london hugo plate
  init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
      curl -LO https://github.com/gohugoio/hugo/releases/download/v0.121.1/hugo_0.121.1_Linux-64bit.tar.gz
      tar -xvf hugo_0.121.1_Linux-64bit.tar.gz
      sudo mv hugo /usr/bin/hugo
      rm hugo_0.121.1_Linux-64bit.tar.gz
      hugo version
      npm version
      go version
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
